name: Package Build
run-name: ${{ github.actor }} triggered a new build

on: 
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PIP_ROOT_USER_ACTION: ignore
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      #PIP_NO_CACHE_DIR: 1
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install .[all]
      - name: Format with black
        run: |
          # Settings are configured within pyproject.toml [tool.black]
          black .
      - name: Lint with flake8
        run: |
          # Settings are configured within pyproject.toml [tool.flake8]
          # but overwritten here to change exit behaviour
          # Stop the build if there are critical syntax issues.
          # Critical pyflakes errors (F)
          # Critical pycodestyle errors (E)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Only report all other syntax issues. The GitHub editor is 127 chars wide
          flake8 . --count --select=F,E,W --exit-zero --max-complexity=10 --statistics
        continue-on-error: true
      - name: Test source security
        run: |
          # Settings are configured within pyproject.toml [tool.bandit]
          bandit -c pyproject.toml -r .
      - name: Run unit tests
        run: pytest .
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Wheels using PEP 517/518
        # when using --no-deps all dependencies have to be already available
        run: pip wheel --no-deps --wheel-dir dist .
      
